/* qspi_flash.c - minimal W25Q256 support using HAL QSPI
 * - probe JEDEC ID
 * - enter 4-byte addressing mode
 * - (optional) enable memory-mapped mode
 */

#include "qspi_flash.h"
#include "quadspi.h"
#include <stdio.h>
#include <string.h>

/* External QSPI handle defined in quadspi.c (generated by CubeMX) */
extern QSPI_HandleTypeDef hqspi;

/* Timeouts */
#define QSPI_CMD_TIMEOUT  HAL_QSPI_TIMEOUT_DEFAULT_VALUE

/* Winbond W25Q256 JEDEC ID expected: 0xEF 0x40 0x19 */
static const uint8_t W25Q256_JEDEC[3] = {0xEF, 0x40, 0x19};

HAL_StatusTypeDef QSPI_ReadJEDECID(uint8_t *id)
{
  QSPI_CommandTypeDef sCommand;
  memset(&sCommand, 0, sizeof(sCommand));

  sCommand.InstructionMode   = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction       = 0x9F; /* JEDEC ID */
  sCommand.AddressMode       = QSPI_ADDRESS_NONE;
  sCommand.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;
  sCommand.DataMode          = QSPI_DATA_1_LINE;
  sCommand.DummyCycles       = 0;
  sCommand.NbData            = 3;

  if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
  {
    return HAL_ERROR;
  }

  if (HAL_QSPI_Receive(&hqspi, id, QSPI_CMD_TIMEOUT) != HAL_OK)
  {
    return HAL_ERROR;
  }

  return HAL_OK;
}

HAL_StatusTypeDef QSPI_Enter_4Byte_AddressMode(void)
{
  QSPI_CommandTypeDef sCommand;
  memset(&sCommand, 0, sizeof(sCommand));

  /* Some flashes require Write Enable before certain commands; for
   * Enter 4-byte mode (0xB7) Winbond typically does not need WE,
   * but sending a Write Enable is harmless.
   */
  /* Write Enable */
  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction = 0x06; /* Write Enable */
  sCommand.AddressMode = QSPI_ADDRESS_NONE;
  sCommand.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;
  sCommand.DataMode = QSPI_DATA_NONE;
  sCommand.DummyCycles = 0;
  sCommand.NbData = 0;
  if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
  {
    return HAL_ERROR;
  }

  /* Enter 4-byte address mode */
  sCommand.Instruction = 0xB7; /* Enter 4-byte address mode */
  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.AddressMode = QSPI_ADDRESS_NONE;
  sCommand.DataMode = QSPI_DATA_NONE;
  sCommand.NbData = 0;

  if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
  {
    return HAL_ERROR;
  }

  return HAL_OK;
}

HAL_StatusTypeDef QSPI_EnableMemoryMappedMode(void)
{
  QSPI_CommandTypeDef sCommand;
  QSPI_MemoryMappedTypeDef memMappedCfg;
  memset(&sCommand, 0, sizeof(sCommand));
  memset(&memMappedCfg, 0, sizeof(memMappedCfg));

  /* Configure the command for memory-mapped read (Fast Read, 0x0B)
   * We use 1-line mode here for compatibility. DummyCycles = 8 is typical
   * for 0x0B fast read.
   */
  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction = 0x0B; /* Fast Read */
  sCommand.AddressMode = QSPI_ADDRESS_1_LINE;
  sCommand.AddressSize = QSPI_ADDRESS_32_BITS; /* after entering 4-byte mode */
  sCommand.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;
  sCommand.DataMode = QSPI_DATA_1_LINE;
  sCommand.DummyCycles = 8;

  memMappedCfg.TimeOutActivation = QSPI_TIMEOUT_COUNTER_DISABLE;

  if (HAL_QSPI_MemoryMapped(&hqspi, &sCommand, &memMappedCfg) != HAL_OK)
  {
    return HAL_ERROR;
  }

  return HAL_OK;
}

HAL_StatusTypeDef QSPI_Flash_Init(void)
{
  uint8_t id[3];
  if (QSPI_ReadJEDECID(id) != HAL_OK)
  {
    printf("QSPI: JEDEC read failed\r\n");
    return HAL_ERROR;
  }

  printf("QSPI: JEDEC ID: %02X %02X %02X\r\n", id[0], id[1], id[2]);

  if (id[0] == W25Q256_JEDEC[0] && id[1] == W25Q256_JEDEC[1] && id[2] == W25Q256_JEDEC[2])
  {
    printf("QSPI: Detected Winbond W25Q256\r\n");
  }
  else
  {
    printf("QSPI: Unknown flash (expected EF 40 19)\r\n");
  }

  /* Enter 4-byte address mode for >16MB flash */
  if (QSPI_Enter_4Byte_AddressMode() != HAL_OK)
  {
    printf("QSPI: Enter 4-byte address mode failed\r\n");
    /* Not fatal; continue */
  }
  else
  {
    printf("QSPI: Entered 4-byte address mode\r\n");
  }

  /* Optionally enable memory-mapped mode. Caller may choose to call
   * QSPI_EnableMemoryMappedMode() explicitly when desired.
   */

  return HAL_OK;
}

/*---------------------------------------------------------------------------
 * QSPI_Read: indirect read from QSPI Flash
 *---------------------------------------------------------------------------
 * Uses Fast Read (0x0B) command with 4-byte address mode.
 * Supports single-line instruction, address, and data.
 */
HAL_StatusTypeDef QSPI_Read(uint32_t addr, uint8_t *buf, uint32_t len)
{
  QSPI_CommandTypeDef sCommand;
  memset(&sCommand, 0, sizeof(sCommand));

  sCommand.InstructionMode   = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction       = 0x0B;  /* Fast Read */
  sCommand.AddressMode       = QSPI_ADDRESS_1_LINE;
  sCommand.AddressSize       = QSPI_ADDRESS_32_BITS;
  sCommand.Address           = addr;
  sCommand.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;
  sCommand.DataMode          = QSPI_DATA_1_LINE;
  sCommand.DummyCycles       = 8;
  sCommand.NbData            = len;

  if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
  {
    return HAL_ERROR;
  }

  if (HAL_QSPI_Receive(&hqspi, buf, QSPI_CMD_TIMEOUT) != HAL_OK)
  {
    return HAL_ERROR;
  }

  return HAL_OK;
}

/*---------------------------------------------------------------------------
 * QSPI_WriteEnable: send Write Enable (0x06) command
 *---------------------------------------------------------------------------
 */
static HAL_StatusTypeDef QSPI_WriteEnable(void)
{
  QSPI_CommandTypeDef sCommand;
  memset(&sCommand, 0, sizeof(sCommand));

  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction     = 0x06;  /* Write Enable */
  sCommand.AddressMode     = QSPI_ADDRESS_NONE;
  sCommand.DataMode        = QSPI_DATA_NONE;
  sCommand.DummyCycles     = 0;

  return HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT);
}

/*---------------------------------------------------------------------------
 * QSPI_WaitBusy: poll status register until WIP (Write In Progress) clears
 *---------------------------------------------------------------------------
 */
static HAL_StatusTypeDef QSPI_WaitBusy(uint32_t timeout_ms)
{
  QSPI_CommandTypeDef sCommand;
  uint8_t sr;
  uint32_t tickstart = HAL_GetTick();

  memset(&sCommand, 0, sizeof(sCommand));
  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction     = 0x05;  /* Read Status Register 1 */
  sCommand.AddressMode     = QSPI_ADDRESS_NONE;
  sCommand.DataMode        = QSPI_DATA_1_LINE;
  sCommand.DummyCycles     = 0;
  sCommand.NbData          = 1;

  do
  {
    if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
      return HAL_ERROR;
    if (HAL_QSPI_Receive(&hqspi, &sr, QSPI_CMD_TIMEOUT) != HAL_OK)
      return HAL_ERROR;
    if ((sr & 0x01) == 0)  /* WIP bit cleared */
      return HAL_OK;
    if ((HAL_GetTick() - tickstart) > timeout_ms)
      return HAL_TIMEOUT;
  } while (1);
}

/*---------------------------------------------------------------------------
 * QSPI_SectorErase: erase 4KB sector
 *---------------------------------------------------------------------------
 */
HAL_StatusTypeDef QSPI_SectorErase(uint32_t addr)
{
  QSPI_CommandTypeDef sCommand;

  if (QSPI_WriteEnable() != HAL_OK)
    return HAL_ERROR;

  memset(&sCommand, 0, sizeof(sCommand));
  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction     = 0x20;  /* Sector Erase (4KB) */
  sCommand.AddressMode     = QSPI_ADDRESS_1_LINE;
  sCommand.AddressSize     = QSPI_ADDRESS_32_BITS;
  sCommand.Address         = addr;
  sCommand.DataMode        = QSPI_DATA_NONE;
  sCommand.DummyCycles     = 0;

  if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
    return HAL_ERROR;

  /* Wait for erase to complete (max ~400ms for W25Q256 sector erase) */
  return QSPI_WaitBusy(500);
}

/*---------------------------------------------------------------------------
 * QSPI_Write: page program (max 256 bytes)
 *---------------------------------------------------------------------------
 * W25Q256 page size is 256 bytes. Address must be page-aligned if crossing
 * page boundaries. For now, caller ensures single-page writes.
 */
HAL_StatusTypeDef QSPI_Write(uint32_t addr, const uint8_t *buf, uint32_t len)
{
  QSPI_CommandTypeDef sCommand;

  if (len > 256)
    return HAL_ERROR;  /* Max 256 bytes per page */

  if (QSPI_WriteEnable() != HAL_OK)
    return HAL_ERROR;

  memset(&sCommand, 0, sizeof(sCommand));
  sCommand.InstructionMode = QSPI_INSTRUCTION_1_LINE;
  sCommand.Instruction     = 0x02;  /* Page Program */
  sCommand.AddressMode     = QSPI_ADDRESS_1_LINE;
  sCommand.AddressSize     = QSPI_ADDRESS_32_BITS;
  sCommand.Address         = addr;
  sCommand.DataMode        = QSPI_DATA_1_LINE;
  sCommand.DummyCycles     = 0;
  sCommand.NbData          = len;

  if (HAL_QSPI_Command(&hqspi, &sCommand, QSPI_CMD_TIMEOUT) != HAL_OK)
    return HAL_ERROR;

  if (HAL_QSPI_Transmit(&hqspi, (uint8_t *)buf, QSPI_CMD_TIMEOUT) != HAL_OK)
    return HAL_ERROR;

  /* Wait for program to complete (max ~3ms for W25Q256 page program) */
  return QSPI_WaitBusy(10);
}
