/**
 * @file jpeg_frames.h
 * @brief 5 test JPEG frames (320x320) embedded in firmware
 *
 * Generated by Python/Pillow. Each frame is a solid color background
 * with a frame number and a circle in the center.
 *
 * Frame table: {offset, size} for each frame within the data blob.
 */
#ifndef __JPEG_FRAMES_H__
#define __JPEG_FRAMES_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Raw JPEG data blob (all 5 frames concatenated).
 * Declared in jpeg_frames_data.h (generated by xxd -i).
 * Note: the names use the full path, but since they're static const
 * in the header, they are included inline in animation.c. */
#define jpeg_frames_data \
    _Users_lemonliu_IOT_STM32_H743_ALIENTEK_CubeIDE_Core_Src_jpeg_frames_bin
#define jpeg_frames_data_len \
    _Users_lemonliu_IOT_STM32_H743_ALIENTEK_CubeIDE_Core_Src_jpeg_frames_bin_len

#define JPEG_FRAMES_COUNT   5

/* Frame offset/size table (index into jpeg_frames_data) */
typedef struct {
    uint32_t offset;
    uint32_t size;
} JPEG_FrameEntry;

static const JPEG_FrameEntry jpeg_frame_table[JPEG_FRAMES_COUNT] = {
    {     0,  3618 },  /* Frame 1: Red   */
    {  3618,  3368 },  /* Frame 2: Green */
    {  6986,  3869 },  /* Frame 3: Blue  */
    { 10855,  3631 },  /* Frame 4: Yellow */
    { 14486,  3510 },  /* Frame 5: Cyan  */
};

#ifdef __cplusplus
}
#endif

#endif /* __JPEG_FRAMES_H__ */