/* video_frames.h - external symbols for embedded frames_hdr.bin
 *
 * Generated by: arm-none-eabi-objcopy -I binary -O elf32-littlearm
 *              --rename-section .data=.rodata.video frames_hdr.bin test_frames.o
 *
 * frames_hdr.bin format (header + frame table, NO pixel data):
 *   [0..3]   num_frames (uint32_t LE)
 *   [4..7]   version (uint32_t LE)
 *   [8..]    frame table: N * {offset:4B LE, size:4B LE}
 *
 * Frame data (raw RGB565) is stored externally on QSPI Flash,
 * programmed via UART (see scripts/program_frames.py).
 */
#ifndef __VIDEO_FRAMES_H__
#define __VIDEO_FRAMES_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Start/end of embedded binary data (header + table only, in Flash .rodata.video) */
extern const uint8_t _binary_test_frames_bin_start[];
extern const uint8_t _binary_test_frames_bin_end[];

/* Size of embedded binary (header + table only) */
#define VIDEO_FRAMES_BIN_SIZE  ((uint32_t)(_binary_test_frames_bin_end - _binary_test_frames_bin_start))

/* QSPI Flash offset where raw frame data begins (after header + table) */
#define QSPI_DATA_OFFSET       4096U  /* sector-aligned, after header+table */

/* Size of each raw RGB565 frame (320x320x2) */
#define FRAME_RAW_SIZE         204800U

/* Header at offset 0 */
typedef struct {
    uint32_t num_frames;
    uint32_t version;       /* 7 = raw RGB565 (no compression) */
} VideoFramesHeader;

/* Frame table entry at offset 8 + index * 8 */
typedef struct {
    uint32_t offset;   /* offset of raw data within QSPI Flash */
    uint32_t size;     /* raw data size in bytes (always FRAME_RAW_SIZE) */
} VideoFrameEntry;

#ifdef __cplusplus
}
#endif

#endif /* __VIDEO_FRAMES_H__ */