#!/usr/bin/env python3
"""Convert PNG images to LVGL C array format (true color with alpha)
Output matches the format used by brightness_icons.h:
  - LV_IMG_CF_TRUE_COLOR_ALPHA
  - 3 bytes per pixel: RGB565 (2 bytes, little-endian) + Alpha (1 byte)
  - uint8_t array

Usage: python3 scripts/convert_filter_icons_c_array.py
Output: Core/Src/icon_resource/filter_icons.h
"""
import os
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = os.path.join(SCRIPT_DIR, '..', 'Core', 'Src', 'icon_resource', 'filters')
OUTPUT_HEADER = os.path.join(SCRIPT_DIR, '..', 'Core', 'Src', 'icon_resource', 'filter_icons.h')


def sanitize_name(filename):
    name = os.path.splitext(filename)[0]
    name = name.replace(' ', '_').replace('*', '_').replace('-', '_').replace('.', '_')
    while '__' in name:
        name = name.replace('__', '_')
    name = name.rstrip('_')
    if name and name[0].isdigit():
        name = '_' + name
    return name


def rgb565_le(r, g, b):
    """Convert 8-bit RGB to 16-bit RGB565 in little-endian bytes.
    Returns (low_byte, high_byte).
    RGB565 bit layout: RRRR RGGG GGGB BBBB
    little-endian: byte0 = GGGG GBBB BBBB (low), byte1 = RRRR RGGG (high)
    """
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    # RGB565 = RRRR RGGG GGGB BBBB
    high = (r5 << 3) | (g6 >> 3)       # RRRR RGGG
    low = ((g6 & 0x07) << 5) | b5      # GGGB BBBB
    return low, high


def main():
    files = sorted([f for f in os.listdir(INPUT_DIR) if f.endswith('.png')])
    if not files:
        print('No PNG files found in', INPUT_DIR)
        return

    parts = []
    parts.append('/* Auto-generated by convert_filter_icons_c_array.py */')
    parts.append('#ifndef FILTER_ICONS_H')
    parts.append('#define FILTER_ICONS_H')
    parts.append('')
    parts.append('#include "lvgl.h"')
    parts.append('')

    for fname in files:
        path = os.path.join(INPUT_DIR, fname)
        var = sanitize_name(fname)
        print(f'Processing {fname} -> {var}...')

        with Image.open(path) as img:
            img = img.convert('RGBA')
            w, h = img.size
            data = img.getdata()

        # 3 bytes per pixel: RGB565_lo + RGB565_hi + Alpha
        total_bytes = w * h * 3
        parts.append(f'/* {fname} - {w}x{h} */')
        parts.append(f'static const uint8_t {var}_data[{total_bytes}] = {{')

        line = '    '
        col = 0
        for (r, g, b, a) in data:
            lo, hi = rgb565_le(r, g, b)
            line += f'0x{lo:02X}, 0x{hi:02X}, 0x{a:02X}, '
            col += 3
            if col % 12 == 0:  # 4 pixels per line (4 * 3 = 12 bytes)
                parts.append(line)
                line = '    '
                col = 0
        if col > 0:
            parts.append(line)

        parts.append('};')
        parts.append(f'const lv_img_dsc_t {var} = {{')
        parts.append('  .header.always_zero = 0,')
        parts.append(f'  .header.w = {w},')
        parts.append(f'  .header.h = {h},')
        parts.append(f'  .data_size = {total_bytes},')
        parts.append('  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,')
        parts.append(f'  .data = {var}_data,')
        parts.append('};')
        parts.append('')

    parts.append('#endif /* FILTER_ICONS_H */')
    parts.append('')

    with open(OUTPUT_HEADER, 'w') as f:
        f.write('\n'.join(parts))

    print('')
    print('Generated', OUTPUT_HEADER)
    print(f'  {len(files)} images converted')


if __name__ == '__main__':
    main()