#!/usr/bin/env python3
"""Convert PNG images in icon_resource/air_quality to LVGL C array header file."""

import os
from PIL import Image

INPUT_DIR = os.path.join(os.path.dirname(__file__),
                         "../Core/Src/icon_resource/air_quality")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__),
                          "../Core/Src/icon_resource")
OUTPUT_HEADER = os.path.join(OUTPUT_DIR, "air_quality_icons.h")


def rgb565(r, g, b):
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5


def png_to_lvgl_c_array(png_path, var_name):
    img = Image.open(png_path).convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())
    data = []
    for r, g, b, a in pixels:
        rgb = rgb565(r, g, b)
        data.append(rgb & 0xFF)
        data.append((rgb >> 8) & 0xFF)
        data.append(a)
    lines = []
    lines.append(f"static const uint8_t {var_name}_data[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hex_str},")
    lines.append("};")
    lines.append(f"const lv_img_dsc_t {var_name} = {{")
    lines.append(f"  .header.always_zero = 0,")
    lines.append(f"  .header.w = {w},")
    lines.append(f"  .header.h = {h},")
    lines.append(f"  .data_size = {len(data)},")
    lines.append(f"  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,")
    lines.append(f"  .data = {var_name}_data,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def sanitize_name(filename):
    name = os.path.splitext(filename)[0]
    name = name.replace('.', '_').replace('-', '_')
    if name and name[0].isdigit():
        name = '_' + name
    return name


def main():
    png_files = sorted([f for f in os.listdir(INPUT_DIR) if f.endswith('.png')])
    if not png_files:
        print('No PNG files found!')
        return
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    parts = []
    parts.append('/* Auto-generated by convert_air_quality_to_lvgl.py */')
    parts.append('#ifndef AIR_QUALITY_ICONS_H')
    parts.append('#define AIR_QUALITY_ICONS_H')
    parts.append('')
    parts.append('#include "lvgl.h"')
    parts.append('')
    for fname in png_files:
        var_name = sanitize_name(fname)
        png_path = os.path.join(INPUT_DIR, fname)
        c_array = png_to_lvgl_c_array(png_path, var_name)
        parts.append(f'/* {fname} */')
        parts.append(c_array)
    parts.append('#endif /* AIR_QUALITY_ICONS_H */')
    parts.append('')
    header_content = '\n'.join(parts)
    with open(OUTPUT_HEADER, 'w') as f:
        f.write(header_content)
    print(f"Generated {OUTPUT_HEADER}")
    print(f"  {len(png_files)} images converted")

if __name__ == '__main__':
    main()
