#!/usr/bin/env python3
"""Embed PNG files in Core/Src/icon_resource/filters as C arrays (raw PNG bytes)
and generate filter_icons.h with lv_img_dsc_t entries using LV_IMG_CF_RAW_ALPHA.
"""
import os
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = os.path.join(SCRIPT_DIR, '..', 'Core', 'Src', 'icon_resource', 'filters')
OUTPUT_HEADER = os.path.join(SCRIPT_DIR, '..', 'Core', 'Src', 'icon_resource', 'filter_icons.h')


def sanitize_name(filename):
    name = os.path.splitext(filename)[0]
    # Replace spaces, asterisks, and other special chars with underscores
    name = name.replace(' ', '_').replace('*', '_').replace('-', '_').replace('.', '_')
    # Collapse multiple underscores
    while '__' in name:
        name = name.replace('__', '_')
    # Remove trailing underscores
    name = name.rstrip('_')
    if name and name[0].isdigit():
        name = '_' + name
    return name


def main():
    files = sorted([f for f in os.listdir(INPUT_DIR) if f.endswith('.png')])
    if not files:
        print('No PNG files found in', INPUT_DIR)
        return
    parts = []
    parts.append('/* Auto-generated by convert_filter_icons.py */')
    parts.append('#ifndef FILTER_ICONS_H')
    parts.append('#define FILTER_ICONS_H')
    parts.append('')
    parts.append('#include "lvgl.h"')
    parts.append('')
    for fname in files:
        path = os.path.join(INPUT_DIR, fname)
        var = sanitize_name(fname)
        # Read image size using Pillow
        try:
            with Image.open(path) as img:
                w, h = img.size
        except Exception:
            w, h = 0, 0
        with open(path, 'rb') as f:
            data = f.read()
        parts.append(f'/* {fname} */')
        parts.append(f'static const uint8_t {var}_data[] = {{')
        # write bytes
        line = '    '
        for i, b in enumerate(data):
            line += f'0x{b:02X}, '
            if (i % 16) == 15:
                parts.append(line)
                line = '    '
        if line.strip():
            parts.append(line)
        parts.append('};')
        parts.append(f'const lv_img_dsc_t {var} = {{')
        parts.append('  .header.always_zero = 0,')
        parts.append(f'  .header.w = {w},')
        parts.append(f'  .header.h = {h},')
        parts.append(f'  .data_size = {len(data)},')
        parts.append('  .header.cf = LV_IMG_CF_RAW_ALPHA,')
        parts.append(f'  .data = {var}_data,')
        parts.append('};')
        parts.append('')
    parts.append('#endif /* FILTER_ICONS_H */')
    parts.append('')
    with open(OUTPUT_HEADER, 'w') as f:
        f.write('\n'.join(parts))
    print('Generated', OUTPUT_HEADER)
    print(f'  {len(files)} images converted')
    for fname in files:
        var = sanitize_name(fname)
        print(f'    {fname} -> {var}')


if __name__ == '__main__':
    main()