#!/usr/bin/env python3
"""
Convert bottom_label.png to C header with RGB565 pixel data.
Scale to width=320, erase watermark text and middle number.
Output: Core/Src/icon_resource/bottom_bar_icons.h

IMPORTANT: Transparent pixels (alpha < 128) are encoded as 0x0001
            (transparent marker), NOT 0x0000. This is because the image
            has a black background (RGB 0,0,0) which is a valid pixel
            value (0x0000 in RGB565). The DrawIcon function skips 0x0001
            but writes 0x0000 (actual black) to the buffer.

Usage: python3 scripts/convert_bottom_icons.py
"""

import os
from PIL import Image

SRC_DIR = os.path.join(os.path.dirname(__file__), '..', 'Core', 'Src', 'icon_resource', 'bottom_bar')
SRC_PNG = os.path.join(SRC_DIR, 'bottom_label.png')
OUT_H   = os.path.join(os.path.dirname(__file__), '..', 'Core', 'Src', 'icon_resource', 'bottom_bar_icons.h')

TARGET_W = 320  # target width in pixels

def rgb565(r, g, b):
    """Convert R8G8B8 to RGB565 little-endian (uint16)."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def main():
    # Open, scale to width=320
    img = Image.open(SRC_PNG).convert('RGBA')
    w, h = img.size
    new_w = TARGET_W
    new_h = round(h * new_w / w)
    img = img.resize((new_w, new_h), Image.LANCZOS)
    print(f"Scaled: {new_w}x{new_h}")

    pixels = list(img.getdata())  # (R,G,B,A) for each pixel

    # Background is black (0,0,0) — confirmed by analysis
    bg_r, bg_g, bg_b = 0, 0, 0
    print(f"Background color: RGB({bg_r},{bg_g},{bg_b})")

    # Erase the large number in the middle (y=55..79)
    # Fill with background color (black)
    for y in range(55, 80):
        for x in range(0, new_w):
            idx = y * new_w + x
            r, g, b, a = pixels[idx]
            if abs(r - bg_r) > 15 or abs(g - bg_g) > 15 or abs(b - bg_b) > 15:
                pixels[idx] = (bg_r, bg_g, bg_b, 255)

    # Erase the "豆包AI生成" watermark at the very bottom-right corner (y=135..140, x=290..320)
    for y in range(135, 141):
        for x in range(290, new_w):
            idx = y * new_w + x
            r, g, b, a = pixels[idx]
            if abs(r - bg_r) > 15 or abs(g - bg_g) > 15 or abs(b - bg_b) > 15:
                pixels[idx] = (bg_r, bg_g, bg_b, 255)

    # Convert to RGB565 bytes (little-endian)
    # Transparent (alpha < 128) -> 0x0001 (transparent marker)
    # Opaque (alpha >= 128) -> normal RGB565 (including 0x0000 for black)
    out = []
    for r, g, b, a in pixels:
        if a < 128:
            # Transparent: use 0x0001 as marker (DrawIcon skips this)
            out.extend([0x01, 0x00])
        else:
            val = rgb565(r, g, b)
            out.append(val & 0xFF)
            out.append((val >> 8) & 0xFF)

    stride = new_w * 2
    total = len(out)
    print(f"Output: {new_w}x{new_h}, {stride} bytes/row, {total} total bytes")

    # Generate header
    lines = []
    lines.append("/* Auto-generated by convert_bottom_icons.py */")
    lines.append("#ifndef BOTTOM_BAR_ICONS_H")
    lines.append("#define BOTTOM_BAR_ICONS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Bottom label: 320x{} RGB565, little-endian bytes */".format(new_h))
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  const uint8_t *data;   /* RGB565 raw data */")
    lines.append("  uint16_t       w;      /* width in pixels */")
    lines.append("  uint16_t       h;      /* height in pixels */")
    lines.append("  uint16_t       stride; /* bytes per row */")
    lines.append("} icon_desc_t;")
    lines.append("")

    lines.append("static const uint8_t bottom_label_data[] = {")
    for i in range(0, len(out), 16):
        chunk = out[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hex_str},")
    lines.append("};")
    lines.append("")

    lines.append("static const icon_desc_t bottom_label = {")
    lines.append(f"  .data   = bottom_label_data,")
    lines.append(f"  .w      = {new_w},")
    lines.append(f"  .h      = {new_h},")
    lines.append(f"  .stride = {stride},")
    lines.append("};")
    lines.append("")

    lines.append("#endif /* BOTTOM_BAR_ICONS_H */")
    lines.append("")

    with open(OUT_H, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Written to {OUT_H}")

if __name__ == '__main__':
    main()