#!/usr/bin/env python3
"""Embed PNG files in Core/Src/icon_resource/air_quality as C arrays (raw PNG bytes)
and generate air_quality_icons.h with lv_img_dsc_t entries using LV_IMG_CF_RAW_ALPHA.
Reads each PNG's width/height (via Pillow) and writes them into the
`lv_img_dsc_t.header.w` and `.header.h` fields so LVGL can know image size.
"""
import os
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = os.path.join(SCRIPT_DIR, '..', 'Core', 'Src', 'icon_resource', 'air_quality')
OUTPUT_HEADER = os.path.join(SCRIPT_DIR, '..', 'Core', 'Src', 'icon_resource', 'air_quality_icons.h')


def sanitize_name(filename):
    name = os.path.splitext(filename)[0]
    name = name.replace('.', '_').replace('-', '_')
    if name and name[0].isdigit():
        name = '_' + name
    return name


def main():
    files = sorted([f for f in os.listdir(INPUT_DIR) if f.endswith('.png')])
    if not files:
        print('No PNG files found in', INPUT_DIR)
        return
    parts = []
    parts.append('/* Auto-generated by embed_air_quality_raw.py */')
    parts.append('#ifndef AIR_QUALITY_ICONS_H')
    parts.append('#define AIR_QUALITY_ICONS_H')
    parts.append('')
    parts.append('#include "lvgl.h"')
    parts.append('')
    for fname in files:
        path = os.path.join(INPUT_DIR, fname)
        var = sanitize_name(fname)
        # Read image size using Pillow
        try:
            with Image.open(path) as img:
                w, h = img.size
        except Exception:
            w, h = 0, 0
        with open(path, 'rb') as f:
            data = f.read()
        parts.append(f'/* {fname} */')
        parts.append(f'static const uint8_t {var}_data[] = {{')
        # write bytes
        line = '    '
        for i, b in enumerate(data):
            line += f'0x{b:02X}, '
            if (i % 16) == 15:
                parts.append(line)
                line = '    '
        if line.strip():
            parts.append(line)
        parts.append('};')
        parts.append(f'const lv_img_dsc_t {var} = {{')
        parts.append('  .header.always_zero = 0,')
        parts.append(f'  .header.w = {w},')
        parts.append(f'  .header.h = {h},')
        parts.append(f'  .data_size = {len(data)},')
        parts.append('  .header.cf = LV_IMG_CF_RAW_ALPHA,')
        parts.append(f'  .data = {var}_data,')
        parts.append('};')
        parts.append('')
    parts.append('#endif /* AIR_QUALITY_ICONS_H */')
    parts.append('')
    with open(OUTPUT_HEADER, 'w') as f:
        f.write('\n'.join(parts))
    print('Generated', OUTPUT_HEADER)

if __name__ == '__main__':
    main()
